part of 'timing_chart.dart';

/// 波形からの自動コメント生成をまとめた `part` ファイル。
///
/// - **目的**: ドメイン寄りのロジック（エッジ検出/文言生成）を `TimingChartState` から切り離し、可読性を上げる。
/// - **実装**: 同一ライブラリ内で private 共有できるよう `extension on TimingChartState` として実装する。
/// - **注意**: `extension` から `setState()` は直接呼べないため、`TimingChartState._setState()` 経由で更新する。
extension _TimingChartAutoCommentsExt on TimingChartState {
  Future<void> _autoGenerateCommentsForCurrentChart() async {
    if (signals.isEmpty) return;

    // 自動生成対象となるコメントを構築
    final List<TimingChartAnnotation> autoComments =
        _buildAutoGeneratedCommentsFromSignals();

    if (autoComments.isEmpty) {
      // 重要とみなせるイベントが見つからなかった場合は簡単なトーストのみ表示
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('自動で挿入できるコメントが見つかりませんでした'),
            duration: Duration(seconds: 2),
          ),
        );
      }
      return;
    }

    _setState(() {
      // 既存の自動生成コメント（IDが "auto" で始まるもの）を削除
      annotations.removeWhere((a) => a.id.startsWith('auto'));

      annotations.addAll(autoComments);
      _forceRepaint();
    });
    _controller?.setAnnotations(annotations);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('自動コメントを ${autoComments.length} 件挿入しました'),
          duration: const Duration(seconds: 2),
        ),
      );
    }
  }

  /// 波形からの自動コメント生成ロジック本体
  ///
  /// - 各可視信号ごとに最大数件のエッジ/長期ONを検出
  /// - HWトリガと出力信号の組み合わせから簡易な遅延コメントを生成
  List<TimingChartAnnotation> _buildAutoGeneratedCommentsFromSignals() {
    final List<TimingChartAnnotation> result = [];
    if (signals.isEmpty) return result;

    // 解析対象の時間長
    final int maxLen = signals
        .map((e) => e.length)
        .fold<int>(0, (prev, len) => math.max(prev, len));
    if (maxLen <= 1) return result;

    // 表示中の行のみを対象にする（なければ全行）
    final List<int> targetRows =
        _visibleIndexes.isNotEmpty
            ? List<int>.from(_visibleIndexes)
            : List<int>.generate(signals.length, (i) => i);

    // 各信号あたり立ち上がり/立ち下がりは「初回のみ」コメントする
    const int maxEdgesPerSignal = 1;
    const int maxTotalAnnotations = 50;
    const int longOnThresholdSteps = 5;
    const int maxTriggerDelaySteps = 20;

    // HWトリガの立ち上がりエッジを記録（後で出力信号との関連コメントに使う）
    final List<_HwTriggerEdge> hwRisingEdges = [];
    final List<_OutputEdge> outputRisingEdges = [];

    for (final rowIndex in targetRows) {
      if (rowIndex < 0 || rowIndex >= signals.length) continue;
      final values = signals[rowIndex];
      if (values.isEmpty) continue;

      final String name =
          (rowIndex < signalNames.length)
              ? signalNames[rowIndex]
              : 'Signal ${rowIndex + 1}';
      final SignalType type =
          (rowIndex < widget.signalTypes.length)
              ? widget.signalTypes[rowIndex]
              : SignalType.input;

      int prev = values.first;
      int runStart = 0;
      int risingCount = 0;
      int fallingCount = 0;

      for (
        int t = 1;
        t < values.length && result.length < maxTotalAnnotations;
        t++
      ) {
        final int v = values[t];
        if (v == prev) continue;

        // 直前までのラン区間 [runStart, t-1] を確定
        if (prev == 1) {
          final int runLength = t - runStart;
          if (runLength >= longOnThresholdSteps &&
              result.length < maxTotalAnnotations) {
            result.add(
              _createAutoAnnotation(
                startTimeIndex: runStart,
                endTimeIndex: t - 1,
                text: _buildLongOnCommentText(name, type, runLength),
              ),
            );
          }
        }

        // エッジ判定
        if (prev == 0 && v == 1) {
          // 立ち上がり
          if (type == SignalType.hwTrigger) {
            hwRisingEdges.add(
              _HwTriggerEdge(rowIndex: rowIndex, timeIndex: t, name: name),
            );
          } else if (type == SignalType.output) {
            outputRisingEdges.add(
              _OutputEdge(rowIndex: rowIndex, timeIndex: t, name: name),
            );
          }

          if (risingCount < maxEdgesPerSignal) {
            result.add(
              _createAutoAnnotation(
                startTimeIndex: t,
                text: _buildEdgeCommentText(name, type, true),
              ),
            );
            risingCount++;
          }
        } else if (prev == 1 && v == 0) {
          // 立ち下がり
          if (fallingCount < maxEdgesPerSignal) {
            result.add(
              _createAutoAnnotation(
                startTimeIndex: t,
                text: _buildEdgeCommentText(name, type, false),
              ),
            );
            fallingCount++;
          }
        }

        runStart = t;
        prev = v;
      }

      // 最後の区間も長いONならコメント
      if (prev == 1) {
        final int runLength = values.length - runStart;
        if (runLength >= longOnThresholdSteps &&
            result.length < maxTotalAnnotations) {
          result.add(
            _createAutoAnnotation(
              startTimeIndex: runStart,
              endTimeIndex: values.length - 1,
              text: _buildLongOnCommentText(name, type, runLength),
            ),
          );
        }
      }

      if (result.length >= maxTotalAnnotations) break;
    }

    // HWトリガ → 出力の遅延コメント（簡易版）
    for (final outEdge in outputRisingEdges) {
      if (result.length >= maxTotalAnnotations) break;
      _HwTriggerEdge? bestTrigger;
      int bestDt = maxTriggerDelaySteps + 1;

      for (final trig in hwRisingEdges) {
        if (trig.timeIndex > outEdge.timeIndex) continue;
        final int dt = outEdge.timeIndex - trig.timeIndex;
        if (dt >= 0 && dt <= maxTriggerDelaySteps && dt < bestDt) {
          bestDt = dt;
          bestTrigger = trig;
        }
      }

      if (bestTrigger != null) {
        result.add(
          _createAutoAnnotation(
            startTimeIndex: bestTrigger.timeIndex,
            endTimeIndex: outEdge.timeIndex,
            text: _buildDelayCommentText(
              bestTrigger.name,
              outEdge.name,
              bestDt,
            ),
          ),
        );
      }
    }

    return result;
  }

  /// エッジ（立ち上がり/立ち下がり）用のコメント文を組み立て
  String _buildEdgeCommentText(String name, SignalType type, bool rising) {
    // 1) まずドメイン固有のルールを優先（役割に沿った短いコメント）
    final String? domainText = _buildDomainSpecificEdgeComment(
      name,
      type,
      rising,
    );
    if (domainText != null) {
      return domainText;
    }

    // 2) 汎用ルールはシンプルな形式に統一
    final String dir = rising ? 'ON' : 'OFF';
    // できるだけ短く：「信号名 ON/OFF」
    return '$name $dir';
  }

  /// 長時間ONが続いた区間用のコメント文を組み立て
  String _buildLongOnCommentText(String name, SignalType type, int steps) {
    // 一部の信号は長時間ONにドメイン固有コメントを割り当て可能
    final String? domainText = _buildDomainSpecificLongOnComment(
      name,
      type,
      steps,
    );
    if (domainText != null) {
      return domainText;
    }

    // 汎用コメントはステップ数を出さず、意味だけを簡潔に
    return '$name 長時間ON';
  }

  /// HWトリガから出力までの遅延コメント文を組み立て
  String _buildDelayCommentText(
    String triggerName,
    String outputName,
    int steps,
  ) {
    // 役割に沿った特別なパターン（例: 一括露光終了 → ワーク搬送）
    final String? domainText = _buildDomainSpecificDelayComment(
      triggerName,
      outputName,
      steps,
    );
    if (domainText != null) {
      return domainText;
    }

    // 汎用コメントもシンプルに
    return '$triggerName → $outputName 遅延 $steps ステップ';
  }

  /// エッジ用のドメイン固有コメント（役割に沿った説明）
  ///
  /// 例) 「一括露光中」がOFFになったタイミングで「ワーク搬送可」など。
  String? _buildDomainSpecificEdgeComment(
    String name,
    SignalType type,
    bool rising,
  ) {
    final normalized = name.replaceAll(' ', '');

    // 一括露光中: OFF になったらワーク搬送が可能
    if (normalized.contains('一括露光中')) {
      if (!rising) {
        return '一括露光終了 → ワーク搬送可';
      } else {
        return '一括露光開始';
      }
    }

    // ここに他のルールを追加可能
    // 例:
    // if (normalized.contains('搬送許可') && rising) {
    //   return 'ワーク搬送開始可（自動）';
    // }

    return null;
  }

  /// 長時間ON用のドメイン固有コメント
  String? _buildDomainSpecificLongOnComment(
    String name,
    SignalType type,
    int steps,
  ) {
    final normalized = name.replaceAll(' ', '');

    // 一括露光中 が長く続いている場合
    if (normalized.contains('一括露光中')) {
      return '一括露光継続中';
    }

    return null;
  }

  /// トリガ→出力の遅延用ドメイン固有コメント
  String? _buildDomainSpecificDelayComment(
    String triggerName,
    String outputName,
    int steps,
  ) {
    final trig = triggerName.replaceAll(' ', '');
    final out = outputName.replaceAll(' ', '');

    // 例: 一括露光トリガ → ワーク搬送用出力 などに合わせて拡張可能
    if (trig.contains('一括露光') && out.contains('搬送')) {
      return '一括露光完了から搬送開始までの遅延 $steps ステップ';
    }

    return null;
  }

  /// 自動コメント用アノテーションインスタンスを生成
  TimingChartAnnotation _createAutoAnnotation({
    required int startTimeIndex,
    int? endTimeIndex,
    required String text,
  }) {
    final String id =
        'auto${DateTime.now().millisecondsSinceEpoch}_${_autoCommentSerial++}';
    return TimingChartAnnotation(
      id: id,
      startTimeIndex: startTimeIndex,
      endTimeIndex: endTimeIndex,
      text: text,
    );
  }
}


